- .drone.yml
- Makefile
- Pkgfile
Using new bldr frontend version which supports multi-arch images.
> feat: support toolchain image with amd64/arm64 architectures

- Pkgfile
This brings in the fix for mutli-arch image manifests.
See https://github.com/talos-systems/bldr/pull/58
> chore: update bldr frontend to 0.2.0-alpha.2.0

- .drone.yml
This switches amd64 builders to be persistent (running outside of the
build) so that cache persists across the builds.
> chore: use persistent builders for caching

- Pkgfile
This adds image labels to link the package back to the repo.
> feat: bump Linux headers, add image labels

- musl/patches/revert-faccessat2.patch
- musl/pkg.yaml
These changes cause issues with seccomp filters which don't include
faccessat2 syscall.
Patch from: https://git.alpinelinux.org/aports/commit/main/musl/?id=26f2d56ad63097cbc61c963ea91c9bd84a62eef4
See also:
* https://bugzilla.redhat.com/show_bug.cgi?id=1869030
* https://bugzilla.redhat.com/show_bug.cgi?id=1900021
> fix: revert faccessat2 changes in libmusl 1.2.2

- Makefile
- Pkgfile
- musl/pkg.yaml
Use v0.2.0-alpha.4 with the same version of musl.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> chore: update bldr version

- binutils/pkg.yaml
This makes `strip` process foreign architectures (in our case,
arm64/amd64 host/target).
See talos-systems/talos#4135
> feat: build binutils multi-arch

- binutils/pkg.yaml
This makes `strip` process foreign architectures (in our case,
arm64/amd64 host/target).
See talos-systems/talos#4135
(cherry picked from commit f7c10985b3b10060d54e1e3c702d9704475975e8)
> backport: feat: build binutils multi-arch

- linux-headers/patches/stddef.h-instead-of-compiler.h.patch
- linux-headers/pkg.yaml
This fixes build failures for new Linux 5.15 kernel.
See also https://github.com/gentoo/musl/commit/e9a03616c762b689a02860e17347eb484d14addf
> fix: patch Linux headers for musl compatibility

- Makefile
- Pkgfile
Also bump the Linux kernel headers to the latest version.
> feat: use bldr with support for SOURCE_DATE_EPOCH

- Makefile
Use the timestamp from repo initial commit as `SOURCE_DATE_EPOCH`
> chore: stable source date epoch

- Makefile
- Pkgfile
Bump kernel to [5.15.63](#45)
Bump bldr to [v0.2.0-alpha.8-frontend](#46)
> chore: bump tools

- Makefile
- Pkgfile
Bump kernel to [5.15.65](#45)
Bump bldr to [v0.2.0-alpha.10](#46)
> chore: update tools

- Pkgfile
> chore: bump kernel to 5.15.72

- Pkgfile
This PR bumps kernel headers to 5.15.82 and mpc to 1.3.0. See #56 for renovate info.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> chore: bump linux and mpc version

- Pkgfile
Partially revert #67
Needs pahole > 1.24. Fix is in pahole dev head https://git.kernel.org/pub/scm/devel/pahole/pahole.git/commit/?h=next&id=bcc648a10cbcd0b96b84ff7c737d56ce70f7b501
> fix: downgrade binutils

- Pkgfile
This PR bumps linux-headers.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> chore: bump linux-headers to 6.1.10

- Pkgfile
Fixes the renovate warning about looking up gmp dependencies. Also update deps.
> fix: renovate config for gmp

- .github/renovate.json
- Pkgfile
Bump dependencies and drop versioning `loose`, instead use proper `matchpackageNames`.
> chore: bump deps

- Pkgfile
Bumping for the upcoming Talos 1.5 release.
> feat: update Linux headers to 6.1.42

- .github/workflows/ci.yaml
- .github/workflows/cron.yaml
Refactor GitHub actions to use the manually retrieved labels as triggers instead on triggering on labels.
> chore: refactor github actions

- Pkgfile
Previous commit does not contain gcc 13.2.0 like it claims. Fixing it.
> chore: bump gcc

- musl/patches/elf.h-add-typedefs.patch
- musl/pkg.yaml
Required for updated stuff in `tools`.
Signed-off-by: Andrey Smirnov <andrey.smirnov@siderolabs.com>
(cherry picked from commit cc75d0e9b45cd61eefa38c803ca1525e03889b30)
> backport: fix: add elf.h patch for new typedefs

- Pkgfile
Revert musl to 1.2.4. Musl 1.2.5 causes a segmentation fault with `depmod`.
> chore: revert musl

- gcc/pkg.yaml
Allows to build position-independent static binaries in the end.
> fix: enable default PIE build mode

- musl/patches/close-range.patch
- musl/pkg.yaml
This fixes fakeroot spinning on CPU forever.
See https://salsa.debian.org/clint/fakeroot/-/commit/80f50cd235f146ffc549018691aafc67277f0076
> fix: add close_range to musl libc

- .github/renovate.json
- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- .github/workflows/weekly.yaml
- Pkgfile
We anticipate to get Linux 6.12 in Talos 1.9.
> feat: update Linux headers to 6.12

- gcc/pkg.yaml
- musl/pkg.yaml
We only build 64-bit, and usrmerge should be used to avoid needing extra env variables.
Signed-off-by: Dmitry Sharshakov <dmitry.sharshakov@siderolabs.com>
> fix: avoid breaking usrmerge, disable multilib

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
Use same buildkit for all builds.
> chore: rekres to unify buildkits

- Pkgfile
- golang123/pkg.yaml
- toolchain/pkg.yaml
Our toolchain contains Go 1.24, build in parallel Go 1.23.8.
It looks like https://github.com/siderolabs/talos/issues/10855 is caused by Go 1.24, as Talos conformance tests started failing on the day Go was updated to 1.24, and also regression testing shows no issues with contianerd built with Go 1.23.8.
Also, containerd upstream is being built/tested with Go 1.23.8 only.
> feat: add a parallel build of Go 1.23

- Pkgfile
- golang123/pkg.yaml
- toolchain/pkg.yaml
Our toolchain contains Go 1.24, build in parallel Go 1.23.8.
It looks like https://github.com/siderolabs/talos/issues/10855 is caused by Go 1.24, as Talos conformance tests started failing on the day Go was updated to 1.24, and also regression testing shows no issues with contianerd built with Go 1.23.8.
Also, containerd upstream is being built/tested with Go 1.23.8 only.
Signed-off-by: Andrey Smirnov <andrey.smirnov@siderolabs.com>
(cherry picked from commit ba4b9acb53c37455a581b5ed34f184656b85537d)
Backports https://github.com/siderolabs/toolchain/pull/139
> backport: feat: add a parallel build of Go 1.23

- Pkgfile
These minor releases include 2 security fixes following the security policy: os/exec: LookPath may return unexpected paths
If the PATH environment variable contains paths which are executables (rather than just directories), passing certain strings to LookPath ("", ".", and ".."), can result in the binaries listed in the PATH being unexpectedly returned.
Thanks to Olivier Mengué for reporting this issue.
This is CVE-2025-47906 and Go issue https://go.dev/issue/74466.
database/sql: incorrect results returned from Rows.Scan
Cancelling a query (e.g. by cancelling the context passed to one of the query methods) during a call to the Scan method of the returned Rows can result in unexpected results if other queries are being made in parallel. This can result in a race condition that may …
> feat: update Go to 1.24.6

- Pkgfile
These minor releases include 2 security fixes following the security policy: os/exec: LookPath may return unexpected paths
If the PATH environment variable contains paths which are executables (rather than just directories), passing certain strings to LookPath ("", ".", and ".."), can result in the binaries listed in the PATH being unexpectedly returned.
Thanks to Olivier Mengué for reporting this issue.
This is CVE-2025-47906 and Go issue https://go.dev/issue/74466.
database/sql: incorrect results returned from Rows.Scan
Canceling a query (e.g. by canceling the context passed to one of the query methods) during a call to the Scan method of the returned Rows can result in unexpected results if other queries are being made in parallel. This can result in a race condition that may overwrite …
> backport: feat: update Go to 1.24.6
