Pkgfile
See https://github.com/talos-systems/bldr/pull/59
=> chore: update bldr frontend to docker.io/autonomy/bldr:v0.2.0-alpha.2-

.drone.yml, Makefile
Username & registry updates, new docker login.
=> chore: move to GitHub container registry

README.md
This is meant to test to the new arm64 builder.
=> docs: update arch in README

gcc/pkg.yaml
This is going to be used with kernel build.
=> feat: enable GCC plugins

Makefile, Pkgfile
Also bump bldr version.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
=> chore: use diffoscope for rebuild target

Makefile, Pkgfile, README.md
=> chore: rename org

.github/renovate.json, Pkgfile, binutils/pkg.yaml, bootstrap/binutils/pkg.yaml
Add renovate config for dependency updates.
=> feat: add renovate

.github/renovate.json
=> chore: enable renovate dashboard

.github/renovate.json, Pkgfile, linux-headers/pkg.yaml
Use same renovate config across all repos.
=> chore: update renovate config

.drone.yml, Pkgfile
Disable running pipeline for renovate/dependabot pull requests.
=> chore: disable drone for renovate/dependabot

Pkgfile
=> feat: update Linux headers to 5.15.80

Makefile, Pkgfile
=> chore: bump bldr

Pkgfile
Routing updates, but jumping to the next LTS.
=> feat: linux 6.1.1, mpc 1.3.1

.github/renovate.json, Pkgfile
Kernel release series, lowercase github path.
=> chore: fix renovate instructions

Makefile, Pkgfile
=> chore: bump deps

Pkgfile
=> chore: bump kernel

Pkgfile
Last change before cutting release-1.4.
=> feat: update Linux to 6.1.22

.github/workflows/ci.yaml, .github/workflows/slack-notify.yaml, .github/workflows/weekly.yaml, Makefile, Pkgfile
=> feat: rekres, update Linux headers to 6.1.63

musl/patches/elf.h-add-typedefs.patch, musl/patches/revert-faccessat2.patch, musl/pkg.yaml
Commit ae35b84 missed some changes from 9267aecb.
=> fix: musl revert

.github/workflows/ci.yaml, .github/workflows/weekly.yaml, Makefile, Pkgfile
=> feat: update gcc to 13.3.0

.github/workflows/ci.yaml, .github/workflows/weekly.yaml, Makefile, Pkgfile, hack/release.sh
| Package | Update | Change |
|---|---|---|
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.6.44` -> `6.6.47` |
| git://sourceware.org/git/binutils-gdb.git | patch | `2_43` -> `2_43_1` |
=> feat: bump dependencies

.github/workflows/ci.yaml, .github/workflows/weekly.yaml, Pkgfile, binutils/pkg.yaml, bootstrap/gcc/pkg.yaml, hack/release.sh
=> feat: update gcc to 14.2

.github/workflows/ci.yaml, .github/workflows/weekly.yaml, Makefile, Pkgfile
Rekres + Linux 6.6.62 headers.
=> feat: small updates before cutting a release

.github/renovate.json, .github/workflows/ci.yaml, .github/workflows/weekly.yaml, .kres.yaml, Makefile
Rekres to bring renovate under kres.
=> chore: rekres to bring renovate under kres

.github/renovate.json, Makefile
Adjusts local output/multi-platform.
=> chore: rekres to fix reproducibility

Pkgfile
=> backport: feat: update Go toolchain

.github/workflows/ci.yaml, .github/workflows/slack-notify-ci-failure.yaml, .github/workflows/slack-notify.yaml, .github/workflows/stale.yml, .github/workflows/weekly.yaml, Makefile, Pkgfile
| Package | Type | Update | Change |
|---|---|---|---|
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git |  | patch | `6.16.3` -> `6.16.7` |
| | rekres | | |
| [actions/stale](https://redirect.github.com/actions/stale) | action | major | `v9.1.0` -> `v10.0.0` |
| [siderolabs/bldr](https://redirect.github.com/siderolabs/bldr) |  | patch | `v0.5.3` -> `v0.5.4` |
Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>
=> chore: update kernel version and rekres

.github/workflows/ci.yaml, .github/workflows/slack-notify-ci-failure.yaml, .github/workflows/stale.yml, .github/workflows/weekly.yaml, Makefile, Pkgfile
See https://groups.google.com/g/golang-nuts/c/Gxn25BP4MXk/m/3KrM-XBOBAAJ
=> feat: bump go to 1.24.8
